In [1]:
import pandas as pd

df = pd.read_csv("data/thrillers.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6097 entries, 0 to 6096
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   original_title             6097 non-null   object
 1   author                     6097 non-null   object
 2   original_publication_year  6097 non-null   int64
 3   num_pages                  5801 non-null   float64
 4   description                6028 non-null   object
 5   genres                     6097 non-null   object
 6   image_url                  6097 non-null   object
 7   reviews_count              6097 non-null   int64
 8   ratings_count              6097 non-null   int64
 9   avg_rating                 6097 non-null   float64
dtypes: float64(2), int64(3), object(5)
memory usage: 476.5+ KB

In [ ]:
df = df[['original_title', 'description', 'ratings_count']].sort_values(by='ratings_count', ascending=False).head(200)
df = df.drop('ratings_count', axis=1)

,original_title,description,ratings_count
4296,The Hunger Games,Winning will make you famous.\nLosing means ce...,5066596
5406,Harry Potter and the Philosopher's Stone,Harry Potter's life is miserable. His parents ...,4972886
5875,To Kill a Mockingbird,The unforgettable novel of a childhood in a sl...,3402363
3166,Divergent,Paperback features over fifty pages of bonus m...,2277881
5275,Angels & Demons,An ancient secret brotherhood.\nA devastating ...,2126047
...,...,...,...
4204,From Dead to Worse,After the natural disaster of Hurricane Katrin...,162919
3595,The Hunger Games Box Set,"The extraordinary, ground breaking New York Ti...",162121
5328,Timeline,"In an Arizona desert, a man wanders in a daze,...",160870
4987,Darkly Dreaming Dexter,"Meet Dexter Morgan, a polite wolf in sheep's c...",160825
6032,Le Fantome de l'Opera,"First published in French as a serial in 1909,...",159942

In [3]:
df = df.drop('ratings_count', axis=1)
df

,original_title,description
4296,The Hunger Games,Winning will make you famous.\nLosing means ce...
5406,Harry Potter and the Philosopher's Stone,Harry Potter's life is miserable. His parents ...
5875,To Kill a Mockingbird,The unforgettable novel of a childhood in a sl...
3166,Divergent,Paperback features over fifty pages of bonus m...
5275,Angels & Demons,An ancient secret brotherhood.\nA devastating ...
...,...,...
4204,From Dead to Worse,After the natural disaster of Hurricane Katrin...
3595,The Hunger Games Box Set,"The extraordinary, ground breaking New York Ti..."
5328,Timeline,"In an Arizona desert, a man wanders in a daze,..."
4987,Darkly Dreaming Dexter,"Meet Dexter Morgan, a polite wolf in sheep's c..."
6032,Le Fantome de l'Opera,"First published in French as a serial in 1909,..."

In [4]:
df.to_csv('200thrillers.csv')

In [ ]:
import pandas as pd
from transformers import pipeline
import json
from pathlib import Path
import time

# ─────────────────────────────────────────────
# CONFIGURATION  — edit these before running
# ─────────────────────────────────────────────
DATA_PATH       = "200thrillers.csv"   # your 200-book sample
OUTPUT_PATH     = "mood_labels.csv"        # where results are saved
DESCRIPTION_COL = "description"           # column name in your CSV
TITLE_COL       = "original_title"        # column name in your CSV
THRESHOLD       = 0.60                    # minimum confidence to keep a label
BATCH_SIZE      = 10                       # books processed per batch

# Thriller-specific mood taxonomy
MOOD_LABELS = [
    "ominous",
    "sinister",
    "cerebral",
    "disorienting",
    "dark",
    "gore"
]


# ─────────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────────
def load_sample(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)

    # Drop books with no description — can't classify what we can't read
    missing = df[DESCRIPTION_COL].isna().sum()
    if missing > 0:
        print(f"  ⚠  Dropping {missing} books with missing descriptions")
    df = df.dropna(subset=[DESCRIPTION_COL]).reset_index(drop=True)

    print(f"  ✓  Loaded {len(df)} books for classification")
    return df


# ─────────────────────────────────────────────
# CLASSIFY
# ─────────────────────────────────────────────
def classify_moods(df: pd.DataFrame) -> pd.DataFrame:
    print("\nLoading model (first run downloads ~500MB)...")
    classifier = pipeline(
        task="zero-shot-classification",
        model="cross-encoder/nli-MiniLM2-L6-H768",
        device=-1,  # CPU — change to 0 if you have a GPU
    )
    print("  ✓  Model loaded\n")

    results = []
    total   = len(df)
    start   = time.time()

    for i, row in df.iterrows():
        description = str(row[DESCRIPTION_COL]).strip()
        title       = str(row.get(TITLE_COL, f"Book {i}"))

        # Run zero-shot classification
        # multi_label=True means labels are scored independently
        # (a book can be both dark AND suspenseful)
        output = classifier(
            description,
            candidate_labels=MOOD_LABELS,
            multi_label=True,
        )

        # Build score dict: {label: score}
        scores = dict(zip(output["labels"], output["scores"]))

        # Keep only labels above threshold
        moods_above_threshold = {
            label: round(score, 4)
            for label, score in scores.items()
            if score >= THRESHOLD
        }

        # Sort by confidence descending and keep top 3
        TOP_N = 3
        moods_sorted = dict(
            sorted(moods_above_threshold.items(), key=lambda x: x[1], reverse=True)[:TOP_N]
        )           

        results.append({
            TITLE_COL:      title,
            "moods":        json.dumps(list(moods_sorted.keys())),  # label list
            "mood_scores":  json.dumps(moods_sorted),               # full scores
            "mood_count":   len(moods_sorted),
        })

        # Progress + ETA
        elapsed     = time.time() - start
        avg_per_book = elapsed / (i + 1)
        remaining   = avg_per_book * (total - i - 1)
        print(
            f"  [{i+1:>3}/{total}]  {title[:40]:<40}"
            f"  moods: {list(moods_sorted.keys())}"
            f"  ETA: {remaining/60:.1f}min"
        )

    return pd.DataFrame(results)


# ─────────────────────────────────────────────
# DIAGNOSTICS  — quick sanity check on results
# ─────────────────────────────────────────────
def print_diagnostics(results_df: pd.DataFrame):
    print("\n" + "="*60)
    print("DIAGNOSTICS")
    print("="*60)

    # Mood coverage
    all_moods = []
    for moods_json in results_df["moods"]:
        all_moods.extend(json.loads(moods_json))

    from collections import Counter
    mood_counts = Counter(all_moods)

    print("\nMood frequency across all books:")
    for mood, count in mood_counts.most_common():
        bar   = "█" * int(count / len(results_df) * 20)
        pct   = count / len(results_df) * 100
        print(f"  {mood:<20} {bar:<20} {count:>3} books ({pct:.0f}%)")

    # Distribution of mood count per book
    print("\nMoods per book distribution:")
    dist = results_df["mood_count"].value_counts().sort_index()
    for n_moods, count in dist.items():
        print(f"  {n_moods} mood(s): {count} books")

    # Books with NO moods above threshold
    no_mood = results_df[results_df["mood_count"] == 0]
    if len(no_mood) > 0:
        print(f"\n  ⚠  {len(no_mood)} books got no mood above threshold {THRESHOLD}:")
        for _, row in no_mood.iterrows():
            print(f"     - {row[TITLE_COL]}")
        print(f"  → Consider lowering THRESHOLD from {THRESHOLD} to 0.15")
    else:
        print(f"\n  ✓  All books received at least one mood label")

    print("="*60)


# ─────────────────────────────────────────────
# SAVE
# ─────────────────────────────────────────────
def save_results(results_df: pd.DataFrame, original_df: pd.DataFrame):
    # Merge mood results back onto original dataframe
    final_df = original_df.merge(results_df, on=TITLE_COL, how="left")
    final_df.to_csv(OUTPUT_PATH, index=False)
    print(f"\n  ✓  Results saved to {OUTPUT_PATH}")
    print(f"     Columns added: moods, mood_scores, mood_count")


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
def main():
    print("="*60)
    print("ZERO-SHOT MOOD CLASSIFICATION")
    print(f"Model:     cross-encoder/nli-MiniLM2-L6-H768")
    print(f"Labels:    {MOOD_LABELS}")
    print(f"Threshold: {THRESHOLD}")
    print("="*60 + "\n")

    df         = load_sample(DATA_PATH)
    results_df = classify_moods(df)

    print_diagnostics(results_df)
    save_results(results_df, df)

    print("\nDone. Next steps:")
    print("  1. Open mood_labels.csv and spot-check 10-15 books you know well")
    print("  2. If too many books have 0 moods → lower THRESHOLD to 0.15")
    print("  3. If every book gets all 7 moods → raise THRESHOLD to 0.30")
    print("  4. Once happy with results, run on your full 6097-book dataset")


if __name__ == "__main__":
    main()

============================================================
ZERO-SHOT MOOD CLASSIFICATION
Model:     cross-encoder/nli-MiniLM2-L6-H768
Labels:    ['dark', 'mysterious', 'suspenseful', 'fast-paced', 'mind-bending', 'emotional']
Threshold: 0.6
============================================================

  ✓  Loaded 200 books for classification

Loading model (first run downloads ~500MB)...

Device set to use cpu

  ✓  Model loaded

  [  1/200]  The Hunger Games                          moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 5.6min
  [  2/200]  Harry Potter and the Philosopher's Stone  moods: ['mysterious', 'suspenseful', 'fast-paced']  ETA: 4.9min
  [  3/200]  To Kill a Mockingbird                     moods: ['emotional']  ETA: 4.1min
  [  4/200]  Divergent                                 moods: []  ETA: 4.3min
  [  5/200]  Angels & Demons                           moods: ['suspenseful']  ETA: 4.3min
  [  6/200]  Harry Potter and the Prisoner of Azkaban  moods: ['suspenseful', 'fast-paced', 'emotional']  ETA: 4.2min
  [  7/200]  Catching Fire                             moods: []  ETA: 4.1min
  [  8/200]  Man som hatar kvinnor                     moods: ['suspenseful', 'emotional', 'dark']  ETA: 4.0min
  [  9/200]  Harry Potter and the Chamber of Secrets   moods: ['mysterious', 'emotional', 'suspenseful']  ETA: 3.9min
  [ 10/200]  Mockingjay                                moods: []  ETA: 3.8min
  [ 11/200]  Harry Potter and the Deathly Hallows      moods: ['suspenseful']  ETA: 3.7min
  [ 12/200]  Harry Potter and the Order of the Phoeni  moods: ['suspenseful', 'mind-bending', 'emotional']  ETA: 3.5min
  [ 13/200]  Harry Potter and the Half-Blood Prince    moods: ['mysterious', 'suspenseful']  ETA: 3.5min
  [ 14/200]  Lord of the Flies                         moods: ['emotional', 'suspenseful', 'mind-bending']  ETA: 3.4min
  [ 15/200]  The Lovely Bones                          moods: ['emotional', 'suspenseful']  ETA: 3.3min
  [ 16/200]  Gone Girl                                 moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 3.3min
  [ 17/200]  The Da Vinci code                         moods: []  ETA: 3.3min
  [ 18/200]  A Game of Thrones                         moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 3.2min
  [ 19/200]  The Lightning Thief                       moods: ['mysterious', 'suspenseful', 'emotional']  ETA: 3.1min
  [ 20/200]  The Girl on the Train                     moods: ['suspenseful', 'emotional', 'mysterious']  ETA: 3.1min
  [ 21/200]  Jane Eyre                                 moods: []  ETA: 3.0min
  [ 22/200]  City of Bones                             moods: ['suspenseful', 'fast-paced', 'emotional']  ETA: 3.0min
  [ 23/200]  Northern Lights                           moods: ['mysterious', 'mind-bending', 'suspenseful']  ETA: 3.0min
  [ 24/200]  The Curious Incident of the Dog in the N  moods: ['emotional']  ETA: 3.1min
  [ 25/200]  Looking for Alaska                        moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 3.0min
  [ 26/200]  The Shining                               moods: ['suspenseful', 'mysterious']  ETA: 3.0min
  [ 27/200]  The Maze Runner                           moods: ['suspenseful', 'emotional', 'fast-paced']  ETA: 2.9min
  [ 28/200]  The Host                                  moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 2.9min
  [ 29/200]  Holes                                     moods: ['dark', 'suspenseful', 'fast-paced']  ETA: 2.8min
  [ 30/200]  The Secret Garden                         moods: ['mysterious', 'suspenseful', 'emotional']  ETA: 2.8min
  [ 31/200]  Miss Peregrine's Home for Peculiar Child  moods: ['mysterious', 'suspenseful', 'mind-bending']  ETA: 2.7min
  [ 32/200]  The Outsiders                             moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 2.7min
  [ 33/200]  The Picture of Dorian Gray                moods: ['emotional']  ETA: 2.7min
  [ 34/200]  Paper Towns                               moods: ['mysterious', 'suspenseful', 'emotional']  ETA: 2.6min
  [ 35/200]  Flickan som lekte med elden               moods: []  ETA: 2.6min
  [ 36/200]  Jurassic Park                             moods: ['mysterious', 'suspenseful']  ETA: 2.6min
  [ 37/200]  A Time to Kill                            moods: ['emotional', 'suspenseful', 'mind-bending']  ETA: 2.5min
  [ 38/200]  Le Comte de Monte-Cristo                  moods: ['suspenseful', 'emotional']  ETA: 2.5min
  [ 39/200]  Thirteen Reasons Why                      moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 2.5min
  [ 40/200]  Room                                      moods: []  ETA: 2.5min
  [ 41/200]  The Road                                  moods: ['mysterious', 'suspenseful', 'dark']  ETA: 2.4min
  [ 42/200]  The Martian                               moods: ['suspenseful', 'mysterious', 'mind-bending']  ETA: 2.4min
  [ 43/200]  American Gods                             moods: []  ETA: 2.4min
  [ 44/200]  Luftslottet som sprangdes                 moods: ['suspenseful', 'emotional', 'mind-bending']  ETA: 2.4min
  [ 45/200]  Clockwork Angel                           moods: ['suspenseful', 'dark', 'emotional']  ETA: 2.4min
  [ 46/200]  It                                        moods: ['emotional']  ETA: 2.4min
  [ 47/200]  The Memory Keeper's Daughter              moods: ['emotional']  ETA: 2.4min
  [ 48/200]  The Pillars of the Earth                  moods: ['suspenseful', 'emotional', 'fast-paced']  ETA: 2.4min
  [ 49/200]  The Titan's Curse                         moods: ['mysterious', 'suspenseful', 'emotional']  ETA: 2.3min
  [ 50/200]  The Lost Hero                             moods: []  ETA: 2.4min
  [ 51/200]  L'Etranger                                moods: ['mind-bending', 'suspenseful', 'mysterious']  ETA: 2.3min
  [ 52/200]  The Firm                                  moods: ['mysterious', 'suspenseful', 'fast-paced']  ETA: 2.3min
  [ 53/200]  The Night Circus                          moods: ['emotional', 'fast-paced', 'mind-bending']  ETA: 2.3min
  [ 54/200]  The Stand                                 moods: ['dark', 'suspenseful', 'fast-paced']  ETA: 2.3min
  [ 55/200]  Ten Little Niggers                        moods: ['mysterious', 'suspenseful', 'mind-bending']  ETA: 2.2min
  [ 56/200]  The Goldfinch                             moods: ['suspenseful']  ETA: 2.2min
  [ 57/200]  Hush, Hush                                moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 2.2min
  [ 58/200]  Beautiful Creatures                       moods: ['mysterious', 'emotional', 'suspenseful']  ETA: 2.2min
  [ 59/200]  A Clockwork Orange                        moods: ['suspenseful', 'mind-bending', 'dark']  ETA: 2.2min
  [ 60/200]  Digital Fortress                          moods: []  ETA: 2.2min
  [ 61/200]  Prestuplenie i nakazanie                  moods: ['suspenseful', 'fast-paced', 'emotional']  ETA: 2.2min
  [ 62/200]  Dead Until Dark                           moods: ['emotional', 'mysterious', 'dark']  ETA: 2.1min
  [ 63/200]  The Shack: Where Tragedy Confronts Etern  moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 2.1min
  [ 64/200]  Harry Potter and the Cursed Child, Parts  moods: ['dark', 'emotional', 'suspenseful']  ETA: 2.1min
  [ 65/200]  Fallen                                    moods: ['mind-bending', 'mysterious', 'emotional']  ETA: 2.1min
  [ 66/200]  The Lost Symbol                           moods: ['suspenseful', 'fast-paced', 'mind-bending']  ETA: 2.1min
  [ 67/200]  In Cold Blood                             moods: ['suspenseful', 'emotional', 'mind-bending']  ETA: 2.0min
  [ 68/200]  Artemis Fowl                              moods: ['suspenseful', 'mysterious', 'mind-bending']  ETA: 2.0min
  [ 69/200]  Big Little Lies                           moods: ['emotional']  ETA: 2.0min
  [ 70/200]  Interview with the Vampire                moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 2.0min
  [ 71/200]  Dark Places                               moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 2.0min
  [ 72/200]  Fight Club                                moods: ['emotional', 'dark', 'suspenseful']  ETA: 2.0min
  [ 73/200]  Carrie                                    moods: ['emotional', 'mind-bending', 'dark']  ETA: 1.9min
  [ 74/200]  The Gunslinger                            moods: []  ETA: 1.9min
  [ 75/200]  Marked                                    moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 1.9min
  [ 76/200]  The Silence of the Lambs                  moods: ['mysterious', 'suspenseful', 'dark']  ETA: 1.9min
  [ 77/200]  Atonement                                 moods: ['emotional', 'suspenseful']  ETA: 1.9min
  [ 78/200]  Sharp Objects                             moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 1.8min
  [ 79/200]  The Husband's Secret                      moods: []  ETA: 1.8min
  [ 80/200]  Misery                                    moods: ['emotional', 'suspenseful']  ETA: 1.8min
  [ 81/200]  The Devil in the White City: Murder, Mag  moods: []  ETA: 1.8min
  [ 82/200]  Inferno                                   moods: ['suspenseful', 'mysterious', 'mind-bending']  ETA: 1.8min
  [ 83/200]  The Scorch Trials                         moods: []  ETA: 1.8min
  [ 84/200]  The Cuckoo's Calling                      moods: ['mysterious', 'fast-paced', 'emotional']  ETA: 1.8min
  [ 85/200]  World War Z: An Oral History of the Zomb  moods: ['suspenseful']  ETA: 1.8min
  [ 86/200]  Sarah's Key                               moods: ['suspenseful', 'emotional', 'fast-paced']  ETA: 1.8min
  [ 87/200]  Throne of Glass                           moods: []  ETA: 1.8min
  [ 88/200]  The Bourne Identity                       moods: ['mysterious', 'dark', 'suspenseful']  ETA: 1.7min
  [ 89/200]  Clockwork Prince                          moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 1.7min
  [ 90/200]  Rebecca                                   moods: ['emotional', 'mind-bending', 'mysterious']  ETA: 1.7min
  [ 91/200]  The Graveyard Book                        moods: ['emotional', 'suspenseful', 'mind-bending']  ETA: 1.7min
  [ 92/200]  Never Let Me Go                           moods: ['emotional', 'suspenseful']  ETA: 1.7min
  [ 93/200]  Legend                                    moods: ['suspenseful', 'mysterious']  ETA: 1.7min
  [ 94/200]  La sombra del viento                      moods: []  ETA: 1.7min
  [ 95/200]  Extremely Loud and Incredibly Close       moods: ['mysterious', 'fast-paced', 'suspenseful']  ETA: 1.7min
  [ 96/200]  Along Came a Spider                       moods: ['suspenseful', 'fast-paced']  ETA: 1.7min
  [ 97/200]  Treasure Island                           moods: ['emotional', 'suspenseful', 'mind-bending']  ETA: 1.6min
  [ 98/200]  11/22/63                                  moods: ['suspenseful', 'emotional', 'mind-bending']  ETA: 1.6min
  [ 99/200]  Neverwhere                                moods: ['mysterious', 'mind-bending', 'suspenseful']  ETA: 1.6min
  [100/200]  We Were Liars                             moods: ['suspenseful', 'mysterious']  ETA: 1.6min
  [101/200]  Tintenherz                                moods: ['emotional', 'suspenseful']  ETA: 1.6min
  [102/200]  Graceling                                 moods: ['emotional', 'suspenseful']  ETA: 1.5min
  [103/200]  The Bad Beginning                         moods: ['emotional', 'dark']  ETA: 1.5min
  [104/200]  Atlas Shrugged                            moods: ['mysterious', 'suspenseful', 'mind-bending']  ETA: 1.5min
  [105/200]  The Pelican Brief                         moods: ['fast-paced', 'suspenseful', 'mind-bending']  ETA: 1.5min
  [106/200]  The 5th Wave                              moods: ['emotional', 'mysterious', 'dark']  ETA: 1.5min
  [107/200]  The Light Between Oceans                  moods: []  ETA: 1.5min
  [108/200]  Shadow Kiss                               moods: []  ETA: 1.5min
  [109/200]  Kiss the Girls                            moods: ['suspenseful']  ETA: 1.5min
  [110/200]  Safe Haven                                moods: ['mysterious', 'emotional', 'suspenseful']  ETA: 1.4min
  [111/200]  Where'd You Go, Bernadette                moods: []  ETA: 1.4min
  [112/200]  I Am Number Four                          moods: []  ETA: 1.4min
  [113/200]  The Godfather                             moods: ['suspenseful']  ETA: 1.4min
  [114/200]  Frostbite                                 moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 1.4min
  [115/200]  The Strange Case of Dr Jekyll and Mr Hyd  moods: ['mysterious', 'emotional', 'mind-bending']  ETA: 1.4min
  [116/200]  The Death Cure                            moods: ['suspenseful', 'fast-paced', 'dark']  ETA: 1.3min
  [117/200]  Oliver Twist                              moods: []  ETA: 1.3min
  [118/200]  The Casual Vacancy                        moods: ['mysterious', 'emotional', 'suspenseful']  ETA: 1.3min
  [119/200]  White Oleander                            moods: ['emotional', 'mind-bending']  ETA: 1.3min
  [120/200]  Nineteen Minutes                          moods: []  ETA: 1.3min
  [121/200]  A Discovery of Witches                    moods: ['mysterious', 'suspenseful', 'emotional']  ETA: 1.3min
  [122/200]  Clockwork Princess                        moods: []  ETA: 1.3min
  [123/200]  Do Androids Dream of Electric Sheep?      moods: ['mysterious']  ETA: 1.2min
  [124/200]  Salem's Lot                               moods: ['mysterious', 'mind-bending', 'emotional']  ETA: 1.2min
  [125/200]  The Red Pyramid                           moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 1.2min
  [126/200]  1st To Die                                moods: []  ETA: 1.2min
  [127/200]  Blood Promise                             moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 1.2min
  [128/200]  Before I Fall                             moods: []  ETA: 1.2min
  [129/200]  Evermore                                  moods: ['mysterious', 'mind-bending', 'suspenseful']  ETA: 1.2min
  [130/200]  Northanger Abbey                          moods: ['mysterious', 'mind-bending', 'suspenseful']  ETA: 1.1min
  [131/200]  The Pact                                  moods: ['emotional', 'suspenseful', 'dark']  ETA: 1.1min
  [132/200]  Crescendo                                 moods: ['mysterious', 'emotional', 'suspenseful']  ETA: 1.1min
  [133/200]  Spirit Bound                              moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 1.1min
  [134/200]  Daughter of Smoke & Bone                  moods: ['emotional', 'mysterious', 'dark']  ETA: 1.1min
  [135/200]  The Thirteenth Tale                       moods: []  ETA: 1.1min
  [136/200]  Das Parfum. Die Geschichte eines Morders  moods: ['mind-bending']  ETA: 1.1min
  [137/200]  Il nome della rosa                        moods: ['suspenseful', 'mysterious', 'fast-paced']  ETA: 1.0min
  [138/200]  A Study in Scarlet                        moods: ['mysterious', 'dark', 'suspenseful']  ETA: 1.0min
  [139/200]  Storm Front                               moods: ['suspenseful', 'mysterious']  ETA: 1.0min
  [140/200]  Last Sacrifice                            moods: []  ETA: 1.0min
  [141/200]  Fried Green Tomatoes at the Whistle Stop  moods: ['emotional', 'suspenseful']  ETA: 1.0min
  [142/200]  Before I Go to Sleep                      moods: ['fast-paced', 'suspenseful', 'mind-bending']  ETA: 1.0min
  [143/200]  Odd Thomas                                moods: []  ETA: 1.0min
  [144/200]  What Alice Forgot                         moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 0.9min
  [145/200]  Dead to the World                         moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 0.9min
  [146/200]  I, Robot                                  moods: []  ETA: 0.9min
  [147/200]  Hopeless                                  moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 0.9min
  [148/200]  Living Dead in Dallas                     moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 0.9min
  [149/200]  The Historian                             moods: ['suspenseful', 'mysterious', 'dark']  ETA: 0.9min
  [150/200]  Red Dragon                                moods: ['suspenseful', 'emotional', 'mysterious']  ETA: 0.9min
  [151/200]  In the Woods                              moods: ['suspenseful', 'emotional', 'fast-paced']  ETA: 0.8min
  [152/200]  Perfect Chemistry                         moods: ['suspenseful', 'mind-bending', 'mysterious']  ETA: 0.8min
  [153/200]  The City of Ember                         moods: ['mysterious', 'suspenseful', 'dark']  ETA: 0.8min
  [154/200]  Defending Jacob                           moods: ['suspenseful', 'emotional', 'fast-paced']  ETA: 0.8min
  [155/200]  Neuromancer                               moods: ['mind-bending', 'suspenseful', 'fast-paced']  ETA: 0.8min
  [156/200]  Under the Dome                            moods: ['mysterious', 'mind-bending', 'suspenseful']  ETA: 0.8min
  [157/200]  Bel Canto                                 moods: []  ETA: 0.8min
  [158/200]  Silence                                   moods: ['emotional']  ETA: 0.7min
  [159/200]  Hai Bian nokahuka [Umibe no Kafuka]       moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 0.7min
  [160/200]  Untamed: A House of Night Novel           moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 0.7min
  [161/200]  Club Dead                                 moods: ['mysterious', 'suspenseful', 'fast-paced']  ETA: 0.7min
  [162/200]  The Secret History                        moods: ['mind-bending', 'suspenseful', 'mysterious']  ETA: 0.7min
  [163/200]  The Green Mile                            moods: ['suspenseful']  ETA: 0.6min
  [164/200]  The Murder on the Orient Express          moods: ['dark', 'suspenseful', 'mysterious']  ETA: 0.6min
  [165/200]  Crown of Midnight                         moods: ['emotional', 'mysterious', 'suspenseful']  ETA: 0.6min
  [166/200]  Chosen: A House of Night Novel            moods: ['mysterious', 'dark', 'suspenseful']  ETA: 0.6min
  [167/200]  The No. 1 Ladies' Detective Agency        moods: ['suspenseful', 'fast-paced', 'mind-bending']  ETA: 0.6min
  [168/200]  Snow Crash                                moods: ['mind-bending', 'mysterious', 'fast-paced']  ETA: 0.6min
  [169/200]  The Adventures of Sherlock Holmes         moods: []  ETA: 0.6min
  [170/200]  Killing Floor                             moods: ['fast-paced', 'mysterious', 'dark']  ETA: 0.5min
  [171/200]  Speaker for the Dead                      moods: ['mysterious', 'mind-bending', 'suspenseful']  ETA: 0.5min
  [172/200]  The Angel Experiment                      moods: ['mysterious', 'fast-paced', 'mind-bending']  ETA: 0.5min
  [173/200]  The War of the Worlds                     moods: ['mind-bending', 'suspenseful']  ETA: 0.5min
  [174/200]  Torment                                   moods: ['mysterious', 'emotional', 'suspenseful']  ETA: 0.5min
  [175/200]  A Great and Terrible Beauty               moods: ['mysterious', 'dark', 'mind-bending']  ETA: 0.4min
  [176/200]  The Hound of the Baskervilles             moods: ['mind-bending', 'dark', 'suspenseful']  ETA: 0.4min
  [177/200]  The Andromeda Strain                      moods: ['fast-paced', 'suspenseful', 'mysterious']  ETA: 0.4min
  [178/200]  Brat'ia Karamazovy                        moods: []  ETA: 0.4min
  [179/200]  American Psycho                           moods: []  ETA: 0.4min
  [180/200]  Dead as a Doornail                        moods: ['suspenseful', 'mysterious', 'emotional']  ETA: 0.4min
  [181/200]  Midnight in the Garden of Good and Evil   moods: ['suspenseful', 'emotional', 'mind-bending']  ETA: 0.3min
  [182/200]  Post-Mortem                               moods: ['mysterious', 'dark', 'mind-bending']  ETA: 0.3min
  [183/200]  Cloud Atlas                               moods: []  ETA: 0.3min
  [184/200]  All Together Dead                         moods: ['emotional', 'suspenseful', 'fast-paced']  ETA: 0.3min
  [185/200]  Definitely Dead (Sookie Stackhouse, #6)   moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 0.3min
  [186/200]  Cujo                                      moods: ['emotional', 'mind-bending', 'suspenseful']  ETA: 0.2min
  [187/200]  Pretty Little Liars                       moods: ['emotional', 'suspenseful', 'mysterious']  ETA: 0.2min

PermissionError: [Errno 13] Permission denied: 'mood_labels.csv'